import type { SiteConfig } from '~/types'

const config: SiteConfig = {
  site: 'https://hiroki6.dev',
  title: '',
  description:
    'Security research, CTF writeups, and backend engineering',
  author: 'Hiroki Fujino',
  tags: ['Security', 'Backend engineering', 'Malware', 'CTF'],
  socialCardAvatarImage: './src/content/small.jpg',
  font: 'JetBrains Mono Variable',
  pageSize: 6,
  trailingSlashes: false,
  navLinks: [
    {
      name: 'Home',
      url: '/',
    },
    {
      name: 'About',
      url: '/about',
    },
    {
      name: 'Posts',
      url: '/posts',
    },
    {
      name: 'GitHub',
      url: 'https://github.com/Hiroki6',
      external: true,
    },
  ],
  themes: {
    mode: 'select',
    default: 'night-owl',
    include: [
      'andromeeda',
      'aurora-x',
      'ayu-dark',
      'catppuccin-frappe',
      'catppuccin-latte',
      'catppuccin-macchiato',
      'catppuccin-mocha',
      'dark-plus',
      'dracula',
      'dracula-soft',
      'everforest-dark',
      'everforest-light',
      'github-dark',
      'github-dark-default',
      'github-dark-dimmed',
      'github-dark-high-contrast',
      'github-light',
      'github-light-default',
      'github-light-high-contrast',
      'gruvbox-dark-hard',
      'gruvbox-dark-medium',
      'gruvbox-dark-soft',
      'gruvbox-light-hard',
      'gruvbox-light-medium',
      'gruvbox-light-soft',
      'houston',
      'kanagawa-dragon',
      'kanagawa-lotus',
      'kanagawa-wave',
      'laserwave',
      'light-plus',
      'material-theme',
      'material-theme-darker',
      'material-theme-lighter',
      'material-theme-ocean',
      'material-theme-palenight',
      'min-dark',
      'min-light',
      'monokai',
      'night-owl',
      'nord',
      'one-dark-pro',
      'one-light',
      'plastic',
      'poimandres',
      'red',
      'rose-pine',
      'rose-pine-dawn',
      'rose-pine-moon',
      'slack-dark',
      'slack-ochin',
      'snazzy-light',
      'solarized-dark',
      'solarized-light',
      'synthwave-84',
      'tokyo-night',
      'vesper',
      'vitesse-black',
      'vitesse-dark',
      'vitesse-light',
    ],
    overrides: {
      // Improve readability for aurora-x theme
      // 'aurora-x': {
      //   background: '#292929FF',
      //   foreground: '#DDDDDDFF',
      //   warning: '#FF7876FF',
      //   important: '#FF98FFFF',
      //   note: '#83AEFFFF',
      // },
      // Make the GitHub dark theme a little cuter
      // 'github-light': {
      //   accent: 'magenta',
      //   heading1: 'magenta',
      //   heading2: 'magenta',
      //   heading3: 'magenta',
      //   heading4: 'magenta',
      //   heading5: 'magenta',
      //   heading6: 'magenta',
      //   separator: 'magenta',
      //   link: 'list',
      // },
    },
  },
  // Social links to display in the footer.
  socialLinks: {
    github: 'https://github.com/Hiroki6',
    linkedin: 'https://www.linkedin.com/in/hiroki-fujino-502851137/',
    medium: 'https://medium.com/@hirokifujino',
    speakerdeck: 'https://speakerdeck.com/hiroki6',
    email: "hirokifujino0108@gmail.com",
    rss: true,
  },
  giscus: {
    repo: 'Hiroki6/hiroki6-astro',
    repoId: 'R_kgDORHVLRw',
    category: 'General',
    categoryId: 'DIC_kwDORHVLR84C3IbG',
    reactionsEnabled: true, // Enable reactions on post itself
  },
  /*characters: {
    owl: '/owl.webp',
    unicorn: '/unicorn.webp',
    duck: '/duck.webp',
  },*/
}

export default config
